name: Bug report
description: Create a bug report to help us improve
labels:
  - bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: OpenWrt version
      description: The OpenWrt release or commit hash where this bug occurs.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ```. /etc/openwrt_release && echo $DISTRIB_REVISION```
  - type: input
    id: target
    attributes:
      label: OpenWrt target/subtarget
      description: The OpenWrt target and subtarget where this bug is observed.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ```. /etc/openwrt/release && echo $DISTRIB_TARGET```
  - type: input
    id: device
    attributes:
      label: Device
      description: The device exhibiting this bug.
    validations:
      required: true
  - type: dropdown
    id: image_kind
    attributes:
      label: Image kind
      options:
        - Official downloaded image
        - Self-built image
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the reported behaviour.
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: diffconfig
    attributes:
      label: Diffconfig
      description: In case of a self-built image, please attach diffconfig.
  - type: markdown
    attributes:
      value: |
        ```./scripts/diffconfig.sh```
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree to the terms below.
      options:
        - label: I am reporting an issue for OpenWrt, not an unsupported fork.
          required: true
