name: Feature request
description: Request a new feature
labels:
  - feature request
body:
  - type: markdown
    attributes:
      value: |
        The OpenWrt project relies on volunteers. While we appreciate feature requests, we might lack the manpower to handle them. Ideally, you get familiar with the codebase and attempt to contribute the feature yourself. Our active community can assist you.
  - type: textarea
    id: description
    attributes:
      label: Describe desired feature
      description: |
        Clearly describe the desired feature.
    validations:
      required: true
